<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4znsybt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4znsybt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4znsybt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4znsybt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4znsybt\appDevDebugProjectContainer([
    'container.build_hash' => '4znsybt',
    'container.build_id' => '7f8707c5',
    'container.build_time' => 1583165834,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4znsybt');
