<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjm1rhh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjm1rhh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTjm1rhh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTjm1rhh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTjm1rhh\appDevDebugProjectContainer([
    'container.build_hash' => 'Tjm1rhh',
    'container.build_id' => '5eaae6c3',
    'container.build_time' => 1581345308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjm1rhh');
