<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNo60m2y\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNo60m2y/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNo60m2y.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNo60m2y\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNo60m2y\appDevDebugProjectContainer([
    'container.build_hash' => 'No60m2y',
    'container.build_id' => '57039ea9',
    'container.build_time' => 1582553805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNo60m2y');
